version: '3'
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: micro/postgres
    ports:
      - 5432:5432
  db-admin:
    image: dpage/pgadmin4
    ports:
      - 8079:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=nembence1994@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - RABBIT_ADDRESSES=rabbit
