insert into address(id, city, country, house_number, street, zip_code) values(null, null, null, null, null, null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 0, null, 'asd0', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 1, null, 'asd1', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 2, null, 'asd2', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 3, null, 'asd3', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 4, null, 'asd4', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 5, null, 'asd5', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 6, null, 'asd6', null);
insert into amusement_park(id, address_id, capital, entrance_fee, name, total_area) values(null, 1, 7, null, 'asd7', null);
