drop table amusement_park if exists;
create table amusement_park (id bigint generated by default as identity, capital integer, entrance_fee integer,
	name varchar(255), total_area integer, address_id bigint not null, primary key (id));
alter table amusement_park add constraint FKiwh2iy5et2dfioo0sng6re5sd foreign key (address_id) references address;
