drop table amusement_park if exists;
drop table address if exists;
create table address (id bigint generated by default as identity, city varchar(15) not null, country varchar(15) not null,
        house_number varchar(5) not null, street varchar(25) not null, zip_code varchar(10) not null, primary key (id));
create table amusement_park (id bigint generated by default as identity, capital integer, entrance_fee integer,
	name varchar(255), total_area integer, address_id bigint not null, primary key (id));
alter table amusement_park add constraint FKiwh2iy5et2dfioo0sng6re5sd foreign key (address_id) references address;
