server.port: 9000
spring:
  sleuth.sampler.percentage: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/amusement_park
    username: postgres
    password: admin
  jpa:
    open-in-view: false
