server.port: 22222
spring:
  sleuth.sampler.percentage: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: admin
  jpa:
    open-in-view: false
  cloud:
    config:
      allowOverride: true
      overrideSystemProperties: false
